# Generated by Django 5.2.17 on 2026-08-11 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], help_text='Whether this item was lost or found', max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('documents', 'Documents'), ('accessories', 'Accessories'), ('clothing', 'Clothing'), ('books', 'Books'), ('keys', 'Keys'), ('wallet', 'Wallet'), ('other', 'Other')], default='other', max_length=15)),
                ('image', models.ImageField(blank=True, default='', upload_to='lost_found/%Y/%m/')),
                ('location', models.CharField(blank=True, default='', help_text='Where the item was lost/found', max_length=200)),
                ('date', models.DateField(blank=True, help_text='Date the item was lost/found', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lost/Found Item',
                'verbose_name_plural': 'Lost/Found Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
