# Generated by Django 5.2.17 on 2026-08-11 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skills, e.g. ["Python", "React", "ML"]')),
                ('interests', models.JSONField(blank=True, default=list, help_text='List of interests, e.g. ["Web Dev", "AI", "Robotics"]')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social links, e.g. {"github": "url", "linkedin": "url"}')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
