# Generated by Django 5.2.17 on 2026-08-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event Registration', 'verbose_name_plural': 'Event Registrations'},
        ),
    ]
